#!/bin/bash

read -p "Enter path: " path

if [ -d "$path" ]; then
  # List all files in the directory
  echo "List of files in $path:"
  ls -al "$path"
else
  echo "$path is not a directory."
  read -p "Enter the path of a directory: " new_path
  # Check if the new path is a directory
  if [ -d "$new_path" ]; then
    echo "List of files in $new_path:"
    ls -al "$new_path"
  else
    echo "$new_path is not a directory. Exiting script."
    exit 1
  fi
fi
